# Generated by Django 3.1.6 on 2021-03-28 10:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('P', models.JSONField()),
                ('Q', models.JSONField()),
                ('R', models.JSONField()),
                ('S', models.JSONField()),
                ('T', models.JSONField()),
                ('array', models.JSONField()),
            ],
            options={
                'verbose_name': 'Leads',
                'verbose_name_plural': 'Leads',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.BigIntegerField()),
                ('patient_name', models.CharField(max_length=128)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_sinus', models.BooleanField()),
                ('is_regular', models.BooleanField()),
                ('heart_axis', models.CharField(max_length=256)),
                ('conclusion', models.CharField(max_length=512)),
                ('additional_info', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='SourceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.BigIntegerField()),
                ('src_image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'SourceImage',
                'verbose_name_plural': 'SourceImages',
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parameters', serialize=False, to='my_ecg_editor.leads')),
                ('is_P', models.BooleanField()),
                ('QRS_width', models.FloatField()),
                ('QRS_height', models.FloatField()),
                ('R_R', models.FloatField()),
                ('R_Q', models.FloatField()),
            ],
            options={
                'verbose_name': 'Parameters',
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.AddField(
            model_name='leads',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='my_ecg_editor.report'),
        ),
    ]
