# Generated by Django 3.1.6 on 2021-04-03 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecg_editor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameters',
            old_name='R_Q',
            new_name='P_R',
        ),
    ]
